Repository fylein/fyle-accounting-mappings, pull requests merged in 2024-12, with the labels that each got.

#127 fix: add constraint on source employee
  fyle_accounting_mappings/migrations/0027_alter_employeemapping_source_employee.py
  fyle_accounting_mappings/models.py
  setup.py
Labels: size/S

#128 Feat: Add Mixin to add created_by and updated_by for configuration table
  .pylintrc
  fyle_accounting_mappings/models.py
  fyle_accounting_mappings/urls.py
  fyle_accounting_mappings/views.py
  setup.py
Labels: size/L

#129 Feat: Resolve Import Error
  fyle_accounting_mappings/mixins.py
  fyle_accounting_mappings/models.py
  setup.py
Labels: size/M

#130 Feat: add craeted_by, updated_by to mapping_settings
  fyle_accounting_mappings/migrations/0028_auto_20241226_1030.py
  fyle_accounting_mappings/models.py
  setup.py
Labels: size/S
