Repository fylein/fyle-accounting-mappings, pull requests merged in 2025-05, with the labels that each got.

#162 feat: support for handling deletion and recreation in accounting
  fyle_accounting_mappings/models.py
  fyle_accounting_mappings/views.py
  setup.py
Labels: size/L

#163 feat: add fund source retrieval support and feature flags based on brand
  fyle_accounting_library/fyle_platform/branding.py
  fyle_accounting_library/fyle_platform/enums.py
  fyle_accounting_library/fyle_platform/helpers.py
  setup.py
Labels: size/M

#164 chore: add utility enum
  fyle_accounting_library/fyle_platform/enums.py
  setup.py
Labels: size/XS

#165 fix: disable custom field on rename
  fyle_accounting_mappings/models.py
  setup.py
Labels: size/XS

#166 chore: add enums for exchange
  fyle_accounting_library/rabbitmq/enums.py
  setup.py
Labels: size/XS

#167 chore: add qbd standarize change
  fyle_accounting_mappings/models.py
  fyle_accounting_mappings/views.py
  setup.py
Labels: size/XS

#169 feat: Add is_resolved flag to failed_events
  fyle_accounting_library/rabbitmq/migrations/0004_failedevent_is_resolved.py
  fyle_accounting_library/rabbitmq/models.py
  setup.py
Labels: size/S

#170 fix: qbd name
  setup.py
Labels: size/XS

#172 chore: standard import changes for xero
  fyle_accounting_mappings/models.py
  fyle_accounting_mappings/views.py
  setup.py
Labels: size/XS

#174 chore: bump version to 2.2.4 and update app name filters for QuickBooks support
  fyle_accounting_mappings/models.py
  fyle_accounting_mappings/views.py
  setup.py
Labels: size/XS

#175 chore: add Intacct standardize import changes
  fyle_accounting_mappings/models.py
  fyle_accounting_mappings/views.py
  setup.py
Labels: size/XS
