Repository fylein/fyle-accounting-mappings, pull requests merged in 2025-03, with the labels that each got.

#137 feat: Add RMQ data class
  fyle_accounting_library/rabbitmq/data_class.py
  setup.py
Labels: size/XS

#138 fix: RMQ data class
  fyle_accounting_library/rabbitmq/connector.py
  fyle_accounting_library/rabbitmq/data_class.py
  setup.py
Labels: size/S

#139 feat: add common resources module
  fyle_accounting_library/common_resources/__init__.py
  fyle_accounting_library/common_resources/apps.py
  fyle_accounting_library/common_resources/enums.py
  fyle_accounting_library/common_resources/helpers.py
  fyle_accounting_library/common_resources/migrations/0001_initial.py
  fyle_accounting_library/common_resources/migrations/__init__.py
  fyle_accounting_library/common_resources/models.py
  setup.py
Labels: size/M

#141 fix: Xero import state key
  fyle_accounting_library/fyle_platform/models.py
  setup.py
Labels: size/XS

#140 Feat: Add routing key to upload s3.
  fyle_accounting_library/fyle_platform/enums.py
  setup.py
Labels: size/XS

#143 chore: add retry schedule enum
  fyle_accounting_library/fyle_platform/enums.py
  setup.py
Labels: size/XS

#145 feat: add destination_id__in filter for destination attributes
  fyle_accounting_mappings/helpers.py
  fyle_accounting_mappings/views.py
  setup.py
Labels: size/XS

#146 feat: add dimension detail api
  fyle_accounting_library/common_resources/serializers.py
  fyle_accounting_library/common_resources/urls.py
  fyle_accounting_library/common_resources/views.py
  setup.py
Labels: size/S

#147 fix: App specific db cols impl
  fyle_accounting_library/fyle_platform/models.py
  setup.py
Labels: size/XS
