Repository fylein/fyle-accounting-mappings, pull requests merged in 2025-06, with the labels that each got.

#176 feat: add Gitleaks secrets scan workflow
  .github/workflows/secrets-scan.yaml
Labels: size/S

#180 fix: duplicate account sync
  fyle_accounting_mappings/models.py
  setup.py
Labels: size/S

#178 chore: add Task chain executor for RabbitMQ processing
  fyle_accounting_library/rabbitmq/data_class.py
  fyle_accounting_library/rabbitmq/helpers.py
  setup.py
Labels: size/M

#182 fix: multiple cost code sync
  fyle_accounting_mappings/models.py
  setup.py
Labels: size/XS

#184 feat: remove publish and club it with automated release
  .github/workflows/publish-on-version-change.yml
  .github/workflows/pythonpublish.yml
  setup.py
Labels: size/M

#185 chore: version bump for #183
  setup.py
Labels: size/XS
