Repository fylein/fyle-accounting-mappings, pull requests merged in 2025-04, with the labels that each got.

#148 fix: migration dependencies for new setup
  fyle_accounting_library/common_resources/migrations/0001_initial.py
  fyle_accounting_library/rabbitmq/migrations/0001_initial.py
  setup.py
Labels: size/XS

#149 fix: model deletion due to app label
  fyle_accounting_library/rabbitmq/models.py
  setup.py
Labels: size/XS

#150 fix: add rabbitmq label
  fyle_accounting_library/rabbitmq/models.py
  setup.py
Labels: size/XS

#151 chore: Add internal state
  fyle_accounting_library/fyle_platform/constants.py
  setup.py
Labels: size/XS

#152 fix: add internal
  fyle_accounting_library/fyle_platform/enums.py
  setup.py
Labels: size/XS

#153 fix: internal
  fyle_accounting_library/fyle_platform/constants.py
  setup.py
Labels: size/XS

#154 feat: Add internal choices
  fyle_accounting_library/fyle_platform/constants.py
  setup.py
Labels: size/XS

#155 feat: extend support for sage 300
  fyle_accounting_library/fyle_platform/enums.py
  fyle_accounting_library/fyle_platform/helpers.py
  fyle_accounting_library/fyle_platform/models.py
  setup.py
Labels: size/S

#156 Feat: Support for adding mapping for bank account in card mapping
  fyle_accounting_mappings/models.py
  fyle_accounting_mappings/views.py
  setup.py
Labels: size/XS

#159 feat: extend support for qb connector
  fyle_accounting_library/fyle_platform/models.py
  setup.py
Labels: size/XS

#160 Feat: Added support to corporate card mapping to show bank account ma…
  fyle_accounting_mappings/models.py
  fyle_accounting_mappings/serializers.py
  fyle_accounting_mappings/views.py
  setup.py
Labels: size/M

#161 Feat: Small fix
  fyle_accounting_mappings/views.py
  setup.py
Labels: size/XS
